# Generated by Django 5.2.13 on 2026-04-14 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idan_muteruz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('can_access_admin_panel', 'Can access the admin panel')], 'verbose_name': 'profile', 'verbose_name_plural': 'profiles'},
        ),
    ]
