# Generated by Django 5.2.13 on 2026-04-15 20:35

import django.db.models.deletion
import idan_muteruz.upload_utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idan_muteruz', '0003_loginattempt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Profile picture (JPEG, PNG, WebP, or GIF; max 2 MB)', null=True, upload_to=idan_muteruz.upload_utils.avatar_upload_path),
        ),
        migrations.CreateModel(
            name='UserDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='PDF document (max 5 MB)', upload_to=idan_muteruz.upload_utils.document_upload_path)),
                ('original_name', models.CharField(help_text='Display name — the original filename supplied by the uploader', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user document',
                'verbose_name_plural': 'user documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
